name: Daily WHOOP Whatsapp Report

on:
  schedule:
    - cron: "0 2 * * *"   # Runs every day 7:30 AM IST (02:00 UTC)
  workflow_dispatch:      # Allow manual run button

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install requests pillow selenium webdriver-manager

    - name: Run script
      env:
        WHOOP_EMAIL: ${{ secrets.WHOOP_EMAIL }}
        WHOOP_PASSWORD: ${{ secrets.WHOOP_PASSWORD }}
        WHATSAPP_URL: ${{ secrets.WHATSAPP_URL }}
        WHATSAPP_API_KEY: ${{ secrets.WHATSAPP_API_KEY }}
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      run: python main.py
